[font]
size = 11

[font.bold]
family = "Departure Mono"
style = "Bold"

[font.bold_italic]
family = "Departure Mono"
style = "Bold Italic"

[font.italic]
family = "Departure Mono"
style = "Italic"

[font.normal]
family = "Departure Mono"
style = "Regular"

[general]
import = ["/nix/store/xwfbhnyk62h418max9zkd53bxgh803y7-alacritty-theme-0-unstable-2025-05-15/share/alacritty-theme/everforest_light.toml"]

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
dynamic_padding = true

[window.dimensions]
columns = 78
lines = 28

[window.padding]
x = 0
y = 0
